datasets:
  - sift-128-euclidean

index_params:
  - index_type: HNSW
    index_args:
      R: 48
      L: 200
      build_quant: SQ8U

  - index_type: IVF
    index_args:
      nlist: 1024

rebuild: false

search_quants:
  - search_quant: SQ4U
    refine_quant: FP16

topks:
  - 100

efs:
  - 100
  - 200
  - 300

runs: 3

concurrency:
  min: 1
